transferzero/api-documentation

transaction-flow.md
* Added API documentation for XOF:Cash(PayDunya) to github api documentation
https://btcafrica.atlassian.net/browse/BTA-1627
=> BTA-1627-XOF-Payout-Cash-PayDunya-Update-API-Documentation

transaction-flow.md
* Added two new banks supported to NGN Bank List with related ISW code.
https://btcafrica.atlassian.net/browse/BTA-1807
=> BTA-1807 Update NGN banks list in API documentation

transaction-flow.md
This reverts commit b8f8ca57ceae64e37953540e254632ff11afb78d.
=> Revert "BTA-2078 Add XOF::Bank payout details (#8)"

transaction-flow.md
This change adds a section detailing the `create_and_fund` endpoint.
=> Add create_and_fund endpoint

additional-features.md
- Add documentation for new mobile validation
=> BTA-2496 Update Account Validation documentation

_config.yml, _docs/architecture.md
This PR updates the webhook examples links and fixes 1 config deprecation.
=> Fix webhooks examples

_docs/collection-details.md
Split the EUR and GBP systems, and add notes on the GBP side about faster payments.
=> BTA-3220 Update our GBP::Bank collection details to point to our UK account

_docs/example-payments.md, _docs/payout-details.md
[BTA-3866](https://azafinance.atlassian.net/browse/BTA-3866): Update API documentation to implement new `ZAR::Bank` payouts
**Note:** This PR will be merged once the integration is on staging.
[PR API Spec / SDKs updates](https://github.com/bitpesa/bitpesa-api-specification/pull/218)
=> BTA-3866 Upade API documentation to implement new ZAR::Bank payouts

_docs/example-payments.md
I changed prouction to production
=> corrected a typo

_data/docs.yml, _docs/business-transactions.md, _docs/changelog.md, _docs/payout-details.md
Note: this relies on us releasing the 1.9.0 version of our API
=> BTA-4985 Add documentation on how to create business senders

_docs/payout-details.md
Include additional optional XOF cash payout details in TZO documentation
=> BTA-4755-update-xof-cash-details

_docs/additional-features.md
=> BTA-5623 Document API pop on Transferzero API

_docs/changelog.md, _docs/payout-details.md
Add documentation for `GHS::Cash` payouts
=> BTA-5446 Add documentation for GHS::Cash payouts

_docs/additional-features.md
=> BTA-5616 Add mobile_provider documentation for Ghana account validation

_docs/payout-details.md
We stop supporting TZS temporarily, so we are removing documentation from our docs page to avoid confusion.
=> Remove TZS from the supported list

_docs/changelog.md, _docs/collection-details.md
- Update documentation to include XOF Mobile payins
ticket: https://azafinance.atlassian.net/browse/BTA-6366
=> BTA-6366 Update API documentation XOF Mobile collections

_data/docs.yml, _docs/reports.md
Adds a set of instructions for how to use the Report Engine API.
=> Add Report Engine API documentation

_docs/business-transactions.md, _docs/changelog.md, _docs/payout-details.md
Adds business recipient description to ZAR payouts:
- Updates available options for legal entity types and nature of business.
- Remove list of generic bank codes, we now only validate the code is 6 digits in length   
https://azafinance.atlassian.net/browse/BTA-6573
=> BTA-6573 - API docs update

_docs/payout-details.md
https://azafinance.atlassian.net/browse/BTA-6638
=> BTA-6638 Update optional fields info

_docs/payout-details.md
[BTA-6752](https://azafinance.atlassian.net/browse/BTA-6752): [USD::Bank - Glo Currency ] - Update API documentation, API Spec and SDKs
Related to: https://github.com/bitpesa/bitpesa-api-specification/pull/263
Changes
---------
- Added `USD::Bank` to the payout details page.
=> BTA-6752 Update API Documentation with USD::Bank

_docs/payout-details.md
[BTA-6752](https://azafinance.atlassian.net/browse/BTA-6752): [USD::Bank - Glo Currency ] - Update API documentation, API Spec and SDKs
Changes
---------
- Added Access Bank to USD::Bank payments.
=> BTA-6752 Add additional banks to USD::Bank

_docs/changelog.md, _docs/payout-details.md
- Added `KES::Mobile` to the payout details page
- Added `KES::Bank` to the payout details page
- Added 1.15.0 release details to change log
=> BTA-6591-add-kes-bank-and-mobile-to-api-docs

_docs/payout-details.md
[BTA-7041](https://azafinance.atlassian.net/browse/BTA-7041): USD::Cash - Glo Currency - Update API documentation
Changes
---------
- Added `USD::Cash` to the payout details documentation.
- Added available countries for `USD::Bank`.
USD::Cash
USD::Bank
=> BTA-7041 Update API documentation for USD::Cash

_docs/changelog.md, _docs/payout-details.md
[BTA-6708](https://azafinance.atlassian.net/browse/BTA-6708): Add new XOF Bank provider details to documentation
- split Personal and Business API requests to send `first_name` and `last_name` or `name`
- change the `iban` within the example with a valid randomly generated IBAN in BBAN format
=> BTA-6708 Add new XOF Bank provider details to documentation

Gemfile.lock, _docs/individual-payments.md
[BTA-7400](https://azafinance.atlassian.net/browse/BTA-7400)
This PR updates the docs to include GNF/XAF/XOF Mobile expansions
=> BTA-7400: Update docs to include GNF/XAF/XOF Mobile expansions

_docs/individual-payments.md
Only to be merged once the changes internally are out
=> BTA-7643 Make USD::Bank payments optional

_docs/architecture.md, _docs/transaction-flow.md
Add documentation for newly updated Collection architecture
<h2>MENU:</h2>
<hr>
<h2>PAYIN METHOD SECTION:</h2>
<hr>
<h2>WEBHOOKS SECTION:</h2>
=> BTA-7795 Update collection architecture

_docs/additional-features.md
Add notes on how to use collection flow discovery.
Update the example response for a collection transaction to match new spec.
=> BTA-7797 Add collection flow discovery to additional features page

.gitignore, _docs/example-collections.md
Update Collection Examples Doc
=> BTA-7797 Update Collection Examples Doc

_docs/business-payments.md, _docs/example-payments.md, _docs/sandbox-testing.md, generate_sdk_examples.rb
BTA-8016
This PR Adds documentation for Sandbox Payin Endpoint
=> BTA-8016 Update SandBox Paying Documentation

_docs/collection-details.md
Add Instructions for our GHS Mobile Collections
=> BTA-8134 Add GHS Payin instructions to our Collection docs

_docs/changelog.md, _docs/collection-details.md
Update Collections page with OTP flow details.
=> BTA-8232 Add otp flow in collections

_docs/error-handling.md
This PR update the documentation to add new error code 415
=> BTA-8262 Adds Error Code 415

_includes/corridors/transfer_reasons.md
Changed all South Africa related texts to generic texts
=> Update transfer reason

_docs/collection-details.md
Changes
- Add XOF MOBILE COLLECTIONS
- ADD USSD_VOUCHER UX_FLOW 
- Add Instructions for XOS Mobile Collections
Screenshots
=> BTA-8264 Add XOF Mobile Collections 

_docs/error-handling.md
=> BTA-8265 Adds Error Code 434

_docs/individual-payments.md
Add bank code for CITI Bank in NGN.
=> BTA-8567 Add CITI Bank for NGN payouts

_docs/individual-payments.md
BTA-7910: Example for XOF Mobile numbers in international format
=> BTA-7910 Example for XOF Mobile numbers in international format

_docs/collection-details.md
- Add XOF MOBILE COLLECTIONS for Ivory Coast( Orange and MTN)
Previous
Updated
=> [BTA-9007] Update docs for XOF mobile collections in ivory coast

_docs/collection-details.md, _docs/sandbox-testing.md
- Update XOF Collections documentation with asynchronous flow.
- Update sandbox testing documentation with examples based on input
=> BTA-9115 Update XOF collections flow

_docs/collection-details.md
- Add async flow for GHS OTP based collections
=> Bta 9115 ghs otp collections update

_docs/collection-details.md, _docs/sandbox-testing.md
- Add country to XOF payin details
=> BTA-9289 Add country to XOF payin details

Gemfile.lock, _docs/changelog.md, _docs/individual-payments.md, _includes/corridors/xaf-bank.md
BTA-9396 - Add XAF::Bank corridor
=> [BTA-9396] Add XAF::bank Corridor

_docs/business-payments.md
Adds XAF::Bank Business Payout Documentation
=> BTA-9662- Document XAF::BAnk Business Payout

_includes/corridors/brl-bank.md
=> BTA-10166 Add phone number BRL::Bank

_includes/corridors/xaf-bank.md
Add Gabon banks descriptions to XAF:Bank
=> BTA-10379 Add Gabon banks descriptions to XAF:Bank

_docs/individual-payments.md, _includes/corridors/nzd-bank.md
=> BTA-10562 Add NZD Bank in individual payments

_docs/individual-payments.md, _includes/corridors/zmw-bank.md
BTA-10564: Add support for ZMW::Bank payouts
Changes
---------
- Adds `ZMW::Bank` payouts in individual payments page.
=> BTA-10564 Add support for ZMW::Bank payouts

_docs/individual-payments.md, _includes/corridors/zmw-bank.md
=> BTA 10564 add support for zmw bank payouts

_includes/corridors/xaf-bank.md, _includes/corridors/xof-bank.md
Changes:
- Removing Central African Republic (XAF) and Guinea Bissau (XOF) from the available countries.
=> Update XAF and XOF countries

_docs/individual-payments.md, _includes/corridors/cad-bank.md
=> BTA-10566 Add CAD::Bank payouts

_includes/corridors/brl-bank.md
=> Update BRL documentation

_docs/individual-payments.md, _includes/corridors/ugx-bank.md, _includes/corridors/ugx-mobile.md
BTA-10846: Add support for UGX::Bank
Changes
-------
- Adds `UGX::Bank` to `individual-payments` page.
- Moves `UGX::Mobile` to its own corridor in `_includes/corridors` folder.
=> BTA-10846 Add support for UGX::Bank

_includes/corridors/brl-bank.md
Add payment and salary account types.
=> BTA-11203 Add new account types for BRL

_includes/corridors/zmw-bank.md
Changes
---------
- Updates `ZMW` banks list.
=> BTA-11209 Update ZMW banks list

_docs/changelog.md, _docs/individual-payments.md, _includes/corridors/xof-mobile.md
- added new mobile payouts supported countries : Benin,Togo
- updated mobile payouts for Senegal
=> BTA-11126: Add support XOF mobile in (Benin, Togo, Senegal, Burkina faso)

_docs/individual-payments.md
- Add Polaris to USD::Bank (Nigeria)
=> [BTA-11300] Add Polaris to USD::Bank (Nigeria)

_includes/corridors/ugx-mobile.md
Changes
---------
- Adds `mtn` to `UGX::Mobile` corridor's available providers.
=> BTA-11438 Update UGX::Mobile providers

_docs/individual-payments.md, _includes/corridors/kes-mobile.md
=> BTA-11425 Add documentation for KES mobile Payouts

_includes/corridors/zar-bank.md
Removing info about optional email for ZAR transaction
=> BTA-11494 Email mandatory for zar

_docs/individual-payments.md, _includes/corridors/kes-mobile.md
Reverts transferzero/api-documentation#182
=> BTA-11425 Add Back documentation for KES mobile Payouts

_docs/additional-features.md, _docs/individual-payments.md, _includes/corridors/kes-bank.md
=> BTA-11432 Add KES::Bank

_includes/corridors/kes-mobile.md
Changes
-------
- Adds `relationship_to_sender` as an optional field to `KES::Mobile` corridor.
=> BTA-11452 KES::Mobile updates

_docs/additional-features.md
=> BTA-11756 Update Balance Enquiry for Bidvest accounts

_docs/business-payments.md, _docs/example-collections.md, _docs/example-payments.md, _docs/transaction-flow.md, generate_sdk_examples.rb
1. Updates Business Sender Optional Details
2. Fixes Example Generate for Commented Code
=> BTA-11751 Update Business Sender Optional Details

_includes/corridors/ugx-bank.md
Add Stanbic Main HQ as Branch Code
=> BTA-11826 Add Stanbic Bank HQ Branch Code

_docs/business-payments.md
Make Business Sender Mobile Optional
=> BTA-11828 Make Business Sender Mobile Optional

_docs/error-handling.md
=> BTA-11824 Error code 416

_includes/corridors/kes-bank.md, _includes/corridors/kes-mobile.md
=> BTA-11690 Standardise recipient identity types for KES

_includes/corridors/nzd-bank.md
=> BTA-12224 Update banks supported for NZD

_docs/business-payments.md
[BTA-11871 ](https://azafinance.atlassian.net/browse/BTA-11871)add kes bank business payouts|
=> BTA-11871 add kes bank business payouts

_includes/corridors/egp-bank.md
=> BTA-12371 Add required fields for EGP::Bank business senders

_includes/corridors/zmw-bank.md
BTA-12482 : Removed first name and last name on ZMW::Bank business senders
=> BTA-12482-removed-first name-and-last-name-on-zmw-business-senders

_includes/corridors/zar-bank.md
BTA-12471 Add optional narration for ZAR
Individual
Business
=> BTA-12471 Add optional narration for ZAR

_includes/corridors/egp-bank.md
[BTA-12817](https://azafinance.atlassian.net/browse/BTA-12817)
Remove email & phone_number sender requirements for EGP payouts (individuals & businesses)
[BTA-12817]: https://azafinance.atlassian.net/browse/BTA-12817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BTA-12817 Remove email & phone_number sender requirements for EGP payouts 

_docs/transaction-flow.md
=> BTA-12945 Update docs around sender reusability

Gemfile.lock, _docs/business-payments.md, _includes/corridors/ngn-bank.md
=> BTA-12925 Add NGN Business Payouts

_docs/individual-payments.md
=> BTA-12946 Remove GHS::Cash

_includes/corridors/xof-mobile.md
=> [BTA-12948] Remove wave

_docs/business-payments.md, _docs/individual-payments.md, _includes/corridors/ngn-bank.md
Ticket: https://azafinance.atlassian.net/browse/BTA-12878
Screenshots:
- individual payments
- business payments
=> [BTA-12878] Add NGN bank codes

_docs/business-payments.md, _includes/corridors/ugx-bank.md, _includes/corridors/ugx_identity_card_id.md
=> BTA-12935 Add UGX Business Payout

_includes/corridors/kes-bank.md
BTA-13104 Additional banks for KES::Bank corridor
Changes
---------
- Adds `Bank of Baroda` to `KES::Bank` banks list.
=> BTA-13104 Additional banks for KES::Bank corridor

_includes/corridors/egp-bank.md, _includes/corridors/usd-bank-egypt.md
Make beneficiary phone number optional for:
- EGP::Bank
- USD::Bank Egypt
=> BTA-13362 Egypt: Make beneficiary phone number optional

_includes/corridors/xof-bank.md
=> BTA-13517 Xof bank narration

_docs/business-payments.md, _docs/individual-payments.md
- Remove United States USD::Bank
Missing United States USD:Bank
Missing United States USD:Bank
=> [BTA-13537] Remove United States USD::Bank

_includes/corridors/zmw-bank.md
=> BTA-13641 ZMW optional fields

_includes/corridors/zar-bank.md
=> BTA-13842 Add FirstRand Bank

_data/docs.yml, _docs/handling-zar-mandates.md
BTA-13586 Pre-transaction mandate validation
Changes
---------
- Adds pre-transaction (validation) mandates handling documentation.
=> BTA-13586 Pre-transaction mandate validation

_includes/corridors/ngn-bank.md
BTA-14045: Add NGN banks codes
- Add NGN banks codes
=> [BTA-14045] Add NGN banks

_docs/changelog.md, _docs/collection-details.md
BTA-13948 NGN::Bank collection
Adding description for NGN bank transfer collection flow.
=> BTA-13948 NGN::Bank collection

_docs/error-handling.md
Documents Error Code 15 & 16 Under Pending Category
=> BTA-14164 Adds Error Code 16 Under Pending Category

_docs/changelog.md, _docs/individual-payments.md, _includes/corridors/egp-cash.md
BTA-14285 Add EGP::Cash corridor
Changes
---------
- Adds `EGP::Cash` corridor.
=> BTA-14285 Add EGP::Cash corridor

_includes/corridors/ugx-mobile.md
[BTA-14527 ](https://azafinance.atlassian.net/browse/BTA-14527) Updated ugx mobile to capture nationality
=> BTA-14527 Updated ugx mobile to capture nationality

_includes/corridors/kes-bank.md, _includes/corridors/kes-mobile.md
=> BTA-14690 Remove requirement for sender city & street in KES payouts

_docs/individual-payments.md, _includes/corridors/recipient_name.md, _includes/corridors/zar-bank.md
Remove optional fields for ZAR::Bank
=> BTA-14798 Remove optional fields for ZAR::Bank

_includes/corridors/ngn-bank.md
BTA-15033: Add NGN bank codes
- Adds NGN bank codes
=> BTA-15033: Add NGN bank codes

_docs/account-validation.md
BTA-15149 Adds mobile provider validation in transaction flow
Changes
-------
- Adds documentation for mobile provider validation in transaction flow.
=> BTA-15149 Adds mobile provider validation in transaction flow

_includes/corridors/xof-mobile.md
[BTA-15281](https://azafinance.atlassian.net/browse/BTA-15281)
- Add wave as a supported provider for CI and SN
[BTA-15281]: https://azafinance.atlassian.net/browse/BTA-15281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BTA-15281 Add Wave as a supported provider for CI and SN

_docs/transaction-flow.md
BTA-15477: Update docs to add source of funds examples
- Updates API docs to add source of funds examples
=> BTA-15477: Update docs to add source of funds examples

_docs/transaction-flow.md
BTA-15477: Update docs to highlight examples of source of funds
=> BTA-15477: Update docs to highlight examples of source of funds

_docs/handling-zar-mandates.md, _includes/corridors/zar-bank.md
Add notes on handling mandates in production and sandbox.
`ZAR::Bank` individual payments section update:
Mandate in progress section update:
=> BTA-15493 Addition details on pre-transaction mandates

_docs/handling-zar-mandates.md
=> BTA-15703 Remove sendRef from sender metadata, use external_id

_includes/corridors/xof-mobile.md
BTA-15793: Add additional required fields for togo  xof mobile transactions
=> BTA-15793: Add additional required fields for togo  xof mobile transactions
