README.md, transaction-flow.md
https://btcafrica.atlassian.net/browse/BTA-1832
During transaction creation a sender is now updated with the submitted details if the external ID already exists in our database.
This updates the documentation to reflect this.
=> BTA-1832 Update external ID section with sender update information

transaction-flow.md
Add payout method details for XOF::Bank to API documentation. Highlights that the payout method is in beta phase with initial rollout in Senegal and Benin.
Resolves: https://btcafrica.atlassian.net/browse/BTA-2078
=> BTA-2078 Add XOF::Bank payout details

transaction-flow.md
Add payout method details for XOF::Bank to API documentation. Highlights that the payout method is in beta phase with initial rollout in Senegal and Benin.
Resolves: https://btcafrica.atlassian.net/browse/BTA-2078
=> BTA-2078 Add XOF bank payout details

_data/docs.yml, _docs/changelog.md, _docs/error-handling.md, _docs/example-payments.md, _docs/quick-integration.md, _docs/transaction-flow.md
This is mainly to cover cases where transactions are not cancelled in the customer's system because of the error message. It also adds notes around what kind of errors they can receive, and a bit more info on how to handle pending transactions
=> Add notes around error handling and that the transactions need to be cancelled

_docs/crypto.md
This change will document our BTC payin and payout methods.
The page is a separate page that is not linked to by other pages, but can be linked to customers interested in BTC transactions separately.
=> Documenting BTC operations

_docs/changelog.md, _docs/payout-details.md
BTA-3139: Update the TZ0 documetation
Changes
-------
Changes include making sure the docs contain support for sort code and account number for GBP::Bank
=> BTA-3139 Update api documentation to include GBP::Bank FP payout options

_docs/changelog.md
BTA-3866 Update changelog versions
=> BTA-3866 Update changelog versions

_docs/transaction-flow.md
This PR adds a transaction processing state with related explanation to the TZero documentation.
Link to Jira ticket:
https://azafinance.atlassian.net/browse/BTA-5305
=> BTA-5305-Update-processing-state-description-in-docs.transferzero.com

_docs/changelog.md
- Update change log with most recent changes in 1.11.0 SDK release
=> BTA-5526-change-kyc-details-from-payout-method-to-sender-details

_docs/payout-details.md
- This is because recent changes has been made to the api for wizall MAD::CASH and XOF::Mobile
=> Fix: Change identity_type and identity_number to identification_type and identification_number

_docs/payout-details.md
BTA-5712 - Unable to create MAD:Cash transaction when identification_type = "O"
Fix example values for identification_type in MAD::Cash payout details, so it matches the spec:
https://github.com/bitpesa/bitpesa-api-specification/blob/master/definitions/sender.yaml#L146
=> BTA-5712 - Unable to create MAD:Cash transaction when identification_type = "O"

_docs/changelog.md, _docs/payout-details.md
- Add optional country attribute to XOF cash payout details
=> BTA-5460-add-country-to-xof-cash-payout-details

_docs/payout-details.md
As this is no longer a supported payment rail
BEFORE
AFTER
Related PR
https://github.com/bitpesa/bitpesa-api/pull/1405 and https://github.com/bitpesa/bitpesa-api-specification/pull/251
=> BTA-5884 Remove documentation for WARI

_docs/error-handling.md
Adds descriptions for error codes `51 - AML suspicion` and `543 - Error cancellation requested by provider`. Recategorises error code `Banned Sender` into a subset of the AML suspicion errors.
Related Provider Utils updates: https://github.com/bitpesa/provider-utils/pull/30
=> Add AML suspicion and provider cancellation error codes

_docs/error-handling.md
BTA-5684 Fix mistaken categories for the `state_reason_details`
=> BTA-5684 Fix mistaken categories for the state_reason_details

_docs/changelog.md, _docs/payout-details.md
Add documentation covering XOF::Mobile payouts in Ivory Coast, including
the addition of a new (optional) country field for XOF::Mobile payouts
to Senegal.
Related to: https://azafinance.atlassian.net/browse/BTA-5456
=> BTA-5456 Add CI payouts for XOF::Mobile

_docs/payout-details.md
Add a note explaining that for XOF::Mobile payouts to Cote D'Ivoire,
where Orange is the provider, the amount value should be divisible by 5.
Replicates this PR, which has been stuck in CI build state as pending:
https://github.com/transferzero/api-documentation/pull/59
=> Add note regarding XOF::Mobile CI Orange payouts

_docs/payout-details.md
Remove optional sender fields for MAD::Cash from our documentation (sender_city_of_birth, country_of_birth). We did the change in this ticket but we haven't updated the API docs https://azafinance.atlassian.net/browse/BTA-5316
=> Remove optional sender fields for MAD::Cash

_docs/payout-details.md
Note indicating that amounts for XOF:Mobile Ivory Coast Orange payouts should be multiple of 5.
=> Note on XOF:Mobile Ivory Coast Orange amounts

_docs/payout-details.md
[BTA-6477](https://azafinance.atlassian.net/browse/BTA-6477): Make cashplus sender gender field optional with default value
Changes
---------
- Removed references to sender's gender in `payout-details.md`.
=> BTA-6477 Make cashplus sender gender field optional with default value

_docs/payout-details.md
Adds documentation for an optional mobile_provider field available for
UGX::Mobile payouts. Also includes a note in-line with our GHS::Mobile
documentation indicating quicker transaction times where the
mobile_provider is given.
=> BTA-6969 Add mobile_provider field to UGX::Mobile

_data/docs.yml, _docs/business-payments.md, _docs/crypto.md, _docs/example-payments.md, _docs/individual-payments.md, _docs/transaction-flow.md, _includes/topnav.html, _sass/bootswatch/yeti/_variables.scss
[BTA-7084](https://azafinance.atlassian.net/browse/BTA-7084): Update API documentation with recipient type
Changes
---------
- Renamed payout details to individual payments.
- Renamed business transactions to business payments.
- Added Sender type and Recipient type sections to the transaction flow.
- Added recipient type to payments example.
- Moved business recipients details from individual payments (former payout details) to business payments (former business transactions).
=> BTA-7084 Update API documentation with recipient type

_sass/bootswatch/yeti/_variables.scss
[BTA-7084](https://azafinance.atlassian.net/browse/BTA-7084): Update API documentation for recipient type
Changes
---------
- Updated header width css that was causing a misalignment in Firefox browser.
Before:
After:
=> BTA-7084 Fix TZ docs header misalignment

_includes/corridors/zar-bank.md
Adding bank_codes supported in ZAR::Bank corridor in API docs so it is accessible by clients
=> Adding ZAR::Bank bank_codes to API docs

_docs/individual-payments.md, _includes/corridors/xaf-bank.md
[BTA-9584](https://azafinance.atlassian.net/browse/BTA-9584): Update XAF region corridors format
Changes
-------
- Updates the XAF corridors, making them consistent with the West Africa / XOF region format (region/currency first, with payment methods/countries as sub-sections).
**Before:**
**After:**
=> BTA-9584 Update XAF region corridors format

_includes/corridors/zar-bank.md
[BTA-9589](https://azafinance.atlassian.net/browse/BTA-9589): Add new banks to ZAR::Bank
Changes
-------
- Adds the following banks to the supported banks section in `ZAR::Bank`:
```
Habib Overseas Bank Limited 700066	
HBZ Bank 570100	
JP Morgan Bank 432000	
Peoples Bank 720026	
PEP Bank 400001
Permanent Bank 760005
Rand Merchant Bank 261251
Reserve Bank 980172
Unibank Limited 790005
VBS 588000
```
- Re-orders the `ZAR::Bank` banks in alphabetical order.
=> BTA-9589 Add new banks to ZAR::Bank docs

_docs/individual-payments.md
Add Union Bank with bank code 032 to documentation for payouts USD::Bank
linked tickets: https://github.com/bitpesa/bitpesa-api/pull/2136 and https://github.com/bitpesa/bitpesa-utils/pull/401
=> BTA-9555 Add Union Bank to USD Bank Payouts

_docs/business-payments.md, _docs/individual-payments.md, _includes/corridors/xaf-bank.md
Adds Bank Codes For Congo, CAF, Chad and Equatorial Guinea
=> BTA-10438 - Adds Bank Codes For Congo, CAF, Chad and Equatorial Guinea

_includes/corridors/brl-bank.md
Updated examples for BRL::Bank:
=> BTA-10273 Add PIX payments support for BRL Bank

_includes/corridors/zar-bank.md
We were using a non-listed bank code as example creating potential confusion, changed it to a listed one.
=> Bank code example change for a real bank code

_docs/individual-payments.md, _includes/corridors/gnf-mobile.md
Changes
---------
- Adds `orange` as available mobile provider for `GNF::Mobile` corridor.
=> BTA-11155 Add support for orange as mobile provider for GNF::Mobile

_includes/corridors/ugx-mobile.md
Changes
---------
- Removes mentions of `mobile_provider` being optional in `UGX::Mobile` corridor.
=> BTA-11438 Remove optional mobile provider in UGX::Mobile

_docs/additional-features.md
Changes
---------
- Adds `UG` as country and `UGX` as currency in the mobile account validation example.
=> BTA-11451 Add account validation support for UGX::Mobile

_includes/corridors/brl-bank.md
BTA-11617: Add sender identification to BRL::Bank
Changes
---------
- Adds Sender identification disclaimer and details to `BRL::Bank` corridor.
=> BTA-11617 Add sender identification to BRL::Bank

_docs/beta-payments.md, _includes/corridors/brl-bank-beta.md
Changes
---------
- Adds `BRL::Bank` corridor to beta payments (with mandatory `phone_number`).
- Removes `phone_number` from `BRL::Bank` in individual payments.
- Updates `BRL::Bank` banks list in both beta and individual payments.
**Beta Payments:**
**Individual Payments:**
**Banks List:**
=> BTA-11659 BRL::Bank payouts update

_includes/corridors/brl-bank-beta.md, _includes/corridors/brl-bank.md
Changes
---------
- Removes `identity_card_type` from `BRL::Bank` documentation and adds ID types next to `identity_card_id` example in individual and beta payments pages.
**Individual**
**Beta**
=> BTA-11718 BRL::Bank Cleanup

_data/docs.yml, _includes/docs_nav.html
This PR is adding a new menu item in Get Started. It modifies the template in order to be able to reconstruct the correct URL and menu item name when an ID is passed
=> Add Proof of payment to menu in Get Started

_includes/corridors/zmw-bank.md
BTA-12085/BTA-12086: Additional regulatory requirements for ZMW::Bank
Changes
---------
- Adds `transfer_reason` to `ZMW::Bank` payout details.
- Adds mandatory Individual and Business sender details for `ZMW::Bank`.
**Transfer Reason**
**Individual Sender Details**
**Business Sender Details**
=> BTA-12085/BTA-12086 Additional regulatory requirements for ZMW::Bank

_includes/corridors/ugx-bank.md
Adding comment about optional 'postal_code' param for UGX::Bank corridor
=> BTA-12353 Optional ugx:bank postal code

_docs/changelog.md
This PR adds changelog entry for the PHP SDK version upgrade. See https://github.com/bitpesa/bitpesa-api-specification/pull/380
=> Add changelog for PHP SDK version 

_docs/business-payments.md, _docs/individual-payments.md, _includes/corridors/usd-bank.md
[BTA-12636 ](https://azafinance.atlassian.net/browse/BTA-12636): Add support for Nigeria USD::Bank payouts
Update Nigeria USD::Bank & USD::Cash sender requirements
Nigeria USD::Bank Business Payments
Nigeria USD::Bank Individual sender Details Update
Nigeria USD::Cash Individual sender Details Update
=> Bta 12636 Add support for Nigeria USD::Bank payouts 

_docs/changelog.md, _docs/individual-payments.md, _docs/transaction-flow.md, _includes/corridors/usd-bank-egypt.md
BTA-12546: USD::Bank payouts in Egypt
Changes
---------
- Adds support for `USD::Bank` payouts in Egypt.
=> BTA-12546 USD::Bank payouts in Egypt

_docs/changelog.md, _includes/corridors/egp-cash.md
BTA-14455 EGP::Cash reference and recipient email
Changes
---------
- Add optional `email` field for individual payouts on the `EGP::Cash` corridor and updates `changelog.md`.
=> BTA-14455 EGP::Cash reference and recipient email

_docs/changelog.md, _includes/corridors/egp-cash.md
BTA-14522 Make EGP::Cash middle name field mandatory
Changes
---------
- Makes `EGP::Cash` middle name field mandatory and updates the changelog.
=> BTA-14522 Make EGP::Cash middle name field mandatory

_docs/error-handling.md
This PR is adding information to help the API users understand that the ultimate source of truth for a transaction status is the transaction's `state` field
=> BTA-14682 Add transaction state source of truth on error code page

_includes/corridors/egp-bank.md, _includes/corridors/egp-cash.md, _includes/corridors/usd-bank-egypt.md
BTA-14829: Add phone number for egypt must be an egyptian number
Add clarification to API docs: Phone number for Egypt must be Egyptian number
=> BTA-14829: Add phone number for egypt must be an egyptian number

_docs/account-validation.md, _docs/changelog.md
BTA-15285 XAF::Mobile account validation
Changes
-------
- Adds support for `XAF::Mobile` Cameroon account validation via mobile provider (`orange`) and account status (`mtn`).
- Updates the changelog.
=> BTA-15285 XAF::Mobile account validation
